<center>
    <img src="http://sct.inf.utfsm.cl/wp-content/uploads/2020/04/logo_di.png" style="width:60%">
    <h1> INF285 - Computación Científica </h1>
    <h2> Certamen 2 - P1</h2>
    <h2> <a href="#acknowledgements"> [S]cientific [C]omputing [T]eam </a> </h2>
    <h2> Version: 1.00</h2>
</center>

# No debe utilizar bibliotecas adicionales.

In [2]:
import numpy as np

# Pregunta 1 - datos

In [4]:
A0 = np.array([[0.5,0,20],[0,0.2,-4],[0,0,0]])
A1 = np.array(
    [[0.5, 0, 0.1, 0, -1],
    [0, 0.2, -0.4, 1, 0],
    [0, 1  , -2 , 0, 0],
    [1, 2  , -3.8 , 2, 1],
    [-1, 2, -4.2 , 2, -1]])
A2 = np.load('./A2.npy')
A3 = np.load('./A3.npy')
print("shape A2: ",A2.shape)
print("shape A3: ",A3.shape)
print("A2: ",A2)
print("A3: ",A3)

shape A2:  (1000, 200)
shape A3:  (200, 1000)
A2:  [[1.         0.08445892 0.         ... 0.58060583 0.31207517 0.        ]
 [1.         0.00375477 0.         ... 0.56290897 0.15839009 0.        ]
 [1.         0.03337801 0.         ... 0.32188778 0.03282842 0.        ]
 ...
 [1.         0.03121084 0.         ... 0.13904431 0.04571994 0.        ]
 [1.         0.09697913 0.         ... 0.60384098 0.10160144 0.        ]
 [1.         0.03162119 0.         ... 0.38654982 0.29900034 0.        ]]
A3:  [[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


# Pregunta 1 - desarrollo

In [13]:
'''
input:
A       : (ndarray) matriz de mxn
delta   : (double) umbral para definir dependencia lineal

output:
li      : (ndarray) vector 'int64' con indices de columnas linealmente independientes
'''
def find_li_columns_indices(A,delta):
    # Your own code. It may be useful to consider the modified Gram-Schmidt algorithm!
    li = np.array([]) # You must remove this line when you implement your own code!!!!!!
    return li